### ISSUE TITLE
Unable to locate manifest file in tiny-mfa-plugin.zip

### ISSUE THREAD

**Issue by duyanh20200013** [ghmer/custom-governance-plugin#1]
I'm having problems installing plugins on IIQ 8.3.
Anyone have a solution? 
Thanks
![Capture](https://github.com/ghmer/custom-governance-plugin/assets/92638388/63d484f7-fbc8-411c-9179-fff283488445)

**Comment by ghmer** [comment]
wrong repository. Closing this issue.
